schema_version: 1

context:
  version: "0.0.10"

package:
  name: sigmatch
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/sigmatch/sigmatch-${{ version }}.tar.gz
  sha256: ac1e3233cedf19bdfb6e4c42a032b3a381b48c46f597fc1ab613512f75ffb03c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools ==68.0.0
    - pip
  run:
    - python >=${{ python_min }}
    - printo >=0.0.26

tests:
  - python:
      imports:
        - sigmatch
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: A quick way to verify function signatures in Python
  license: MIT
  license_file: LICENSE
  homepage: https://pypi.org/project/sigmatch/
  repository: https://github.com/mutating/sigmatch

extra:
  recipe-maintainers:
    - thewchan
